package com.tutpro.baresip.plus

import androidx.compose.ui.graphics.Color

// HHDesign (бордо #7A0C2A, графит Fluent 2) — G:\HHDesign / github.com/TheRainOfSoul/HHDesign

val Primary = Color(0xFF7A0C2A)
val OnPrimary = Color(0xFFFFFFFF)
val PrimaryContainer = Color(0xFFF6E3E8)
val OnPrimaryContainer = Color(0xFF3D0717)
val Secondary = Color(0xFF424242)
val OnSecondary = Color(0xFFFFFFFF)
val SecondaryContainer = Color(0xFFEBEBEB)
val OnSecondaryContainer = Color(0xFF242424)
val Tertiary = Color(0xFF616161)
val OnTertiary = Color(0xFFFFFFFF)
val TertiaryContainer = Color(0xFFF0F0F0)
val OnTertiaryContainer = Color(0xFF242424)
val Error = Color(0xFFC50F1F)
val OnError = Color(0xFFFFFFFF)
val ErrorContainer = Color(0xFFFDE7E9)
val OnErrorContainer = Color(0xFF751D1F)
val Background = Color(0xFFFAFAFA)
val OnBackground = Color(0xFF242424)
val Surface = Color(0xFFFAFAFA)
val OnSurface = Color(0xFF242424)
val SurfaceVariant = Color(0xFFEBEBEB)
val OnSurfaceVariant = Color(0xFF616161)
val SurfaceContainerLowest = Color(0xFFFFFFFF)
val SurfaceContainerLow = Color(0xFFF5F5F5)
val SurfaceContainer = Color(0xFFF0F0F0)
val SurfaceContainerHigh = Color(0xFFEBEBEB)
val SurfaceContainerHighest = Color(0xFFE0E0E0)
val Outline = Color(0xFF8A8A8A)
val OutlineVariant = Color(0xFFD1D1D1)

val PrimaryDark = Color(0xFFC8445F)  // один primary и для шапок, и для текста: белый на нём 4.7:1, он на фоне 3.5:1
val OnPrimaryDark = Color(0xFFFFFFFF)
val PrimaryContainerDark = Color(0xFF9E1B3A)
val OnPrimaryContainerDark = Color(0xFFFFFFFF)
val SecondaryDark = Color(0xFFD6D6D6)
val OnSecondaryDark = Color(0xFF242424)
val SecondaryContainerDark = Color(0xFF3D3D3D)
val OnSecondaryContainerDark = Color(0xFFFFFFFF)
val TertiaryDark = Color(0xFFADADAD)
val OnTertiaryDark = Color(0xFF242424)
val TertiaryContainerDark = Color(0xFF333333)
val OnTertiaryContainerDark = Color(0xFFFFFFFF)
val ErrorDark = Color(0xFFF1707B)
val OnErrorDark = Color(0xFF3B0509)
val ErrorContainerDark = Color(0xFF751D1F)
val OnErrorContainerDark = Color(0xFFFDE7E9)
val BackgroundDark = Color(0xFF1F1F1F)
val OnBackgroundDark = Color(0xFFFFFFFF)
val SurfaceDark = Color(0xFF1F1F1F)
val OnSurfaceDark = Color(0xFFFFFFFF)
val SurfaceVariantDark = Color(0xFF333333)
val OnSurfaceVariantDark = Color(0xFFD6D6D6)
val SurfaceContainerLowestDark = Color(0xFF141414)
val SurfaceContainerLowDark = Color(0xFF1A1A1A)
val SurfaceContainerDark = Color(0xFF292929)
val SurfaceContainerHighDark = Color(0xFF2E2E2E)
val SurfaceContainerHighestDark = Color(0xFF383838)
val OutlineDark = Color(0xFF8A8A8A)
val OutlineVariantDark = Color(0xFF525252)
